spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/blogish_db?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: blogish
    password: blog1234BLOG!@#$

server:
  servlet:
    context-path: /api